name: learnnfun
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  google_fonts: ^4.0.3
  percent_indicator: ^4.2.3

  cupertino_icons: ^1.0.3
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  firebase_auth: ^4.3.0
  overlay_support: ^2.1.0
  firebase_crashlytics: ^3.0.17
  google_sign_in: ^6.0.2
  dots_indicator:
  carousel_slider: ^4.0.0
  bubble_chart: ^0.4.0
  flutter_svg_provider: ^1.0.3
  confetti: ^0.7.0
  davinci: ^2.0.5
  firebase_storage: ^11.0.16



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0

flutter_icons:
    android: true
    ios: true
    remove_alpha_ios: true
    image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/
      - assets/gifting/
      - assets/basketball/
      - assets/ideation/
      - assets/test/
      - assets/introductionSlider/
      - assets/quiz/
      - assets/BMC/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

